/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmusik;

/**
 *
 * @author Putri
 */
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class RentalMusikFrame extends javax.swing.JFrame {

    /**
     * Creates new form RentalKameraFrame
     */
    public RentalMusikFrame() {
        initComponents();
        
        
        ButtonGroup buttonGroupJenisKelamin = new ButtonGroup();
        buttonGroupJenisKelamin.add(rblaki);
        buttonGroupJenisKelamin.add(rbperempuan);
        
//        // Inisialisasi model tabel dengan kolom-kolom yang sesuai
//        String[] columnNames = {"ID", "Nama", "Jenis Kelamin", "Alamat", "Kamera", "Tambahan", "Tgl Sewa", "Tgl Kembali", "Pembayaran", "Total Hari", "Total Harga"};
//        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
//
//        // Inisialisasi tabel dengan model tabel yang sudah dibuat
//        tabel_data.setModel(tableModel);
//
//        // Tambahkan tabel ke JScrollPane dan tambahkan JScrollPane ke layout
//        JScrollPane scrollPane = new JScrollPane(tabel_data);
//        getContentPane().add(scrollPane, BorderLayout.CENTER);
        
        load_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jToggleButton8 = new javax.swing.JToggleButton();
        btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listkamera = new javax.swing.JList<>();
        cbbaterai = new javax.swing.JCheckBox();
        cbsdcard = new javax.swing.JCheckBox();
        cbtripod = new javax.swing.JCheckBox();
        datesewa = new com.toedter.calendar.JDateChooser();
        datekembali = new com.toedter.calendar.JDateChooser();
        combobayar = new javax.swing.JComboBox<>();
        txttotalhari = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel17 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel18 = new javax.swing.JLabel();
        btnhapus1 = new javax.swing.JButton();
        btnhapus2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dewah\\OneDrive\\Pictures\\oop2.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dewah\\OneDrive\\Pictures\\oop2.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToggleButton8.setBackground(new java.awt.Color(102, 204, 255));
        jToggleButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dewah\\OneDrive\\Pictures\\dw.png")); // NOI18N
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dewah\\OneDrive\\Pictures\\final.png")); // NOI18N
        btn.setText("HAPUS");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(null);

        tabel_data.setBackground(new java.awt.Color(102, 204, 255));
        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "Alamat", "Alat Musik", "Tambahan", "Tanggal Sewa", "Tanggal Kembali", "Pembayaran", "Total Hari"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_data);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 510, 1490, 110);

        btntambah.setBackground(new java.awt.Color(51, 0, 255));
        btntambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntambah.setForeground(new java.awt.Color(255, 255, 255));
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        getContentPane().add(btntambah);
        btntambah.setBounds(1020, 450, 120, 40);

        btnedit.setBackground(new java.awt.Color(0, 204, 0));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("UBAH");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit);
        btnedit.setBounds(880, 450, 124, 44);

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus);
        btnhapus.setBounds(740, 450, 124, 44);

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KARTU IDENTITAS :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 100, 160, 23);

        txtnama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama);
        txtnama.setBounds(120, 200, 332, 28);

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(120, 130, 332, 28);

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NAMA :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 170, 80, 23);

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JENIS KELAMIN :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 240, 140, 23);

        jLabel6.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ALAMAT :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 320, 100, 20);

        rblaki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rblaki.setText("Laki - Laki");
        rblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakiActionPerformed(evt);
            }
        });
        getContentPane().add(rblaki);
        rblaki.setBounds(120, 280, 85, 25);

        rbperempuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbperempuan.setText("Perempuan");
        rbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbperempuanActionPerformed(evt);
            }
        });
        getContentPane().add(rbperempuan);
        rbperempuan.setBounds(120, 260, 140, 25);

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ALAT MUSIK:");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1300, 100, 170, 23);

        jLabel13.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TAMBAHAN :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(780, 310, 130, 23);

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TANGGAL SEWA :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(790, 100, 140, 23);

        jLabel14.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("TANGGAL KEMBALI :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(780, 150, 170, 20);

        jLabel12.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PEMBAYARAN :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(760, 220, 150, 23);

        listkamera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        listkamera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listkamera.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Gitar akustik", "Gitar listrik", "Bass", "Ukulele", "Drum set", "Cajon", "Conga", "Bongo", "Xylophone", "Marimba", "Saxophone", "Flute", "Trumpet", "Trombone", "Klarinet", "Piano", "Keyboard elektronik", "Synthesizer" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listkamera);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1140, 120, 332, 100);

        cbbaterai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbaterai.setText("Mikrofon dan Stand Mikrofon");
        cbbaterai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbateraiActionPerformed(evt);
            }
        });
        getContentPane().add(cbbaterai);
        cbbaterai.setBounds(800, 330, 260, 24);

        cbsdcard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbsdcard.setText("Amplifier gitar/bass");
        cbsdcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsdcardActionPerformed(evt);
            }
        });
        getContentPane().add(cbsdcard);
        cbsdcard.setBounds(800, 350, 180, 24);

        cbtripod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbtripod.setText("Kabel dan aksesori ");
        cbtripod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtripodActionPerformed(evt);
            }
        });
        getContentPane().add(cbtripod);
        cbtripod.setBounds(950, 350, 200, 30);

        datesewa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(datesewa);
        datesewa.setBounds(800, 120, 281, 30);

        datekembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(datekembali);
        datekembali.setBounds(800, 170, 281, 30);

        combobayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combobayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "BRI", "BCA", " " }));
        combobayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobayarActionPerformed(evt);
            }
        });
        getContentPane().add(combobayar);
        combobayar.setBounds(800, 230, 80, 26);

        txttotalhari.setEditable(false);
        txttotalhari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttotalhari.setText("total hari akan muncul saat data ditambah");
        txttotalhari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        txttotalhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalhariActionPerformed(evt);
            }
        });
        getContentPane().add(txttotalhari);
        txttotalhari.setBounds(800, 280, 280, 28);

        jLabel15.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TOTAL HARI :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(780, 260, 130, 23);

        txtalamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtalamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(txtalamat);
        txtalamat.setBounds(120, 340, 332, 26);

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari);
        txtcari.setBounds(210, 450, 392, 40);

        btncari.setBackground(new java.awt.Color(204, 204, 204));
        btncari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        getContentPane().add(btncari);
        btncari.setBounds(620, 450, 72, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CARI NAMA :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(110, 450, 100, 30);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(1179, 24, 0, 0);

        jLabel10.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("-SEWA ALAT MUSIK WAHKYYY-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 30, 1129, 37);

        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 0, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 30, 0, 0);

        jToggleButton1.setBackground(new java.awt.Color(0, 204, 204));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(-10, 440, 1540, 390);

        jLabel17.setBackground(new java.awt.Color(0, 0, 153));
        jLabel17.setFont(new java.awt.Font("Onyx", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("TABLE DATA SEWA ALAT MUSIK");
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 0, 153))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(-30, 380, 1600, 60);

        jToggleButton2.setBackground(new java.awt.Color(0, 0, 153));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(-10, 380, 1550, 60);

        jLabel18.setBackground(new java.awt.Color(0, 0, 153));
        jLabel18.setFont(new java.awt.Font("Onyx", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("TABLE DATA SEWA ALAT MUSIK");
        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 0, 153))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(-30, 380, 1600, 60);

        btnhapus1.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhapus1.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus1.setText("HAPUS");
        btnhapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus1);
        btnhapus1.setBounds(750, 450, 124, 44);

        btnhapus2.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhapus2.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus2.setText("HAPUS");
        btnhapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus2);
        btnhapus2.setBounds(750, 450, 124, 44);

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dewah\\OneDrive\\Pictures\\final.png")); // NOI18N
        btn1.setText("HAPUS");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(850, -410, 690, 1150);

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dewah\\OneDrive\\Pictures\\final.png")); // NOI18N
        btn2.setText("HAPUS");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(-170, -410, 1170, 1150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtripodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtripodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtripodActionPerformed

    private void cbbateraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbateraiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbateraiActionPerformed

    private void combobayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobayarActionPerformed

    private void rblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblakiActionPerformed

    private void rbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbperempuanActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO penyewa (id, nama, jenis_kelamin, alamat, kamera, tambahan, tgl_sewa, tgl_kembali, pembayaran, total_hari) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.Connection conn = koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, txtid.getText());
        pst.setString(2, txtnama.getText());
        
        String jenisKelamin;
        if (rblaki.isSelected()) {
            jenisKelamin = "Laki-laki";
        } else if (rbperempuan.isSelected()) {
            jenisKelamin = "Perempuan";
        } else {
            jenisKelamin = ""; // Atau nilai default lainnya
        }
        
        pst.setString(3, jenisKelamin);
        pst.setString(4, txtalamat.getText());
        
        String kamera = listkamera.getSelectedValue();
            pst.setString(5, kamera);

        StringBuilder tambahan = new StringBuilder();
            if (cbbaterai.isSelected()) tambahan.append("Baterai ");
            if (cbtripod.isSelected()) tambahan.append("Tripod ");
            if (cbsdcard.isSelected()) tambahan.append("SD Card");
            pst.setString(6, tambahan.toString().trim());

            // Get dates from JDateChooser
        java.util.Date tglSewa = datesewa.getDate();
        java.util.Date tglKembali = datekembali.getDate();
        pst.setDate(7, new java.sql.Date(tglSewa.getTime()));
        pst.setDate(8, new java.sql.Date(tglKembali.getTime()));
        pst.setString(9, combobayar.getSelectedItem().toString());
            
        long diff = tglKembali.getTime() - tglSewa.getTime();
            int totalHari = (int) (diff / (1000 * 60 * 60 * 24));
            txttotalhari.setText(String.valueOf(totalHari));
            pst.setInt(10, totalHari);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        load_tabel();
        
        // Tutup PreparedStatement dan Connection
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
 

        
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE penyewa SET nama=?, jenis_kelamin=?, alamat=?, kamera=?, tambahan=?, tgl_sewa=?, tgl_kembali=?, pembayaran=?, total_hari=? WHERE id=?";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtnama.getText());

            String jenisKelamin;
            if (rblaki.isSelected()) {
                jenisKelamin = "Laki-laki";
            } else if (rbperempuan.isSelected()) {
                jenisKelamin = "Perempuan";
            } else {
                jenisKelamin = ""; // Atau nilai default lainnya
            }
            pst.setString(2, jenisKelamin);

            pst.setString(3, txtalamat.getText());

            String kamera = listkamera.getSelectedValue();
            pst.setString(4, kamera);

            StringBuilder tambahan = new StringBuilder();
            if (cbbaterai.isSelected()) tambahan.append("Baterai ");
            if (cbtripod.isSelected()) tambahan.append("Tripod ");
            if (cbsdcard.isSelected()) tambahan.append("SD Card");
            pst.setString(5, tambahan.toString().trim());

            // Get dates from JDateChooser
            java.util.Date tglSewa = datesewa.getDate();
            java.util.Date tglKembali = datekembali.getDate();
            if (tglSewa != null) {
                pst.setDate(6, new java.sql.Date(tglSewa.getTime()));
            } else {
                pst.setNull(6, java.sql.Types.DATE);
            }
            if (tglKembali != null) {
                pst.setDate(7, new java.sql.Date(tglKembali.getTime()));
            } else {
                pst.setNull(7, java.sql.Types.DATE);
            }

            pst.setString(8, combobayar.getSelectedItem().toString());
            
            long diff = tglKembali.getTime() - tglSewa.getTime();
            int totalHari = (int) (diff / (1000 * 60 * 60 * 24));
            txttotalhari.setText(String.valueOf(totalHari));
            pst.setInt(9, totalHari);
            pst.setString(10, txtid.getText());
            
            

            int affectedRows = pst.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                load_tabel(); // Refresh the table to show updated data
            } else {
                JOptionPane.showMessageDialog(null, "Gagal mengubah data. ID tidak ditemukan");
            }

            // Tutup PreparedStatement dan Connection
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
}

        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            // Mendapatkan indeks baris yang dipilih
            int rowIndex = tabel_data.getSelectedRow();

            // Memastikan bahwa baris telah dipilih
            if (rowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus");
                return;
            }

            // Mendapatkan nilai ID dari baris yang dipilih
            String id = tabel_data.getValueAt(rowIndex, 0).toString();

            // Konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Query SQL untuk menghapus data
                String sql = "DELETE FROM penyewa WHERE id=?";
                java.sql.Connection conn = koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);

                // Eksekusi query hapus
                int rowsDeleted = pst.executeUpdate();

                // Menampilkan pesan berhasil atau gagal
                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    load_tabel(); // Refresh the table to show updated data
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data");
                }

                // Menutup PreparedStatement dan Connection
                pst.close();
                conn.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
}

        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txttotalhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalhariActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        // TODO add your handling code here:
        
        int rowIndex = tabel_data.getSelectedRow();
        // Mengambil nilai dari kolom yang sesuai dengan baris yang diklik
        String id = tabel_data.getValueAt(rowIndex, 0).toString();
        String nama = tabel_data.getValueAt(rowIndex, 1).toString();
        String jenisKelamin = tabel_data.getValueAt(rowIndex, 2).toString();
        String alamat = tabel_data.getValueAt(rowIndex, 3).toString();
        String kamera = tabel_data.getValueAt(rowIndex, 4).toString();
        String tambahan = tabel_data.getValueAt(rowIndex, 5).toString();
        String tglSewa = tabel_data.getValueAt(rowIndex, 6).toString();
        String tglKembali = tabel_data.getValueAt(rowIndex, 7).toString();
        String pembayaran = tabel_data.getValueAt(rowIndex, 8).toString();
        String totalHari = tabel_data.getValueAt(rowIndex, 9).toString();

        // Menampilkan nilai dari kolom yang sesuai ke dalam elemen input
        txtid.setText(id);
        txtnama.setText(nama);
        txtalamat.setText(alamat);

        if (jenisKelamin.equals("Laki-laki")) {
            rblaki.setSelected(true);
        } else if (jenisKelamin.equals("Perempuan")) {
            rbperempuan.setSelected(true);
        } else {
            // Reset radio buttons if gender is not recognized
            buttonGroupJenisKelamin.clearSelection();
        }

        // Menetapkan nilai pada list kamera
        listkamera.setSelectedValue(kamera, true);

        // Menetapkan nilai pada checkboxes tambahan
        cbbaterai.setSelected(tambahan.contains("Baterai"));
        cbtripod.setSelected(tambahan.contains("Tripod"));
        cbsdcard.setSelected(tambahan.contains("SD Card"));

        // Menetapkan nilai pada JDateChooser
        try {
            java.util.Date sewaDate = new SimpleDateFormat("yyyy-MM-dd").parse(tglSewa);
            datesewa.setDate(sewaDate);
            java.util.Date kembaliDate = new SimpleDateFormat("yyyy-MM-dd").parse(tglKembali);
            datekembali.setDate(kembaliDate);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // Menetapkan nilai pada combobox pembayaran
        combobayar.setSelectedItem(pembayaran);

        txttotalhari.setText(totalHari);
                
        
        
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        // Ambil teks pencarian dari JTextField txtcari
    String searchTerm = txtcari.getText();
    
    try {
        String sql = "SELECT * FROM penyewa WHERE nama LIKE ?";
        java.sql.Connection conn = koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, "%" + searchTerm + "%");

        ResultSet rs = pst.executeQuery();

        // Clear existing rows in the table model
        DefaultTableModel tableModel = (DefaultTableModel) tabel_data.getModel();
        tableModel.setRowCount(0); // Menghapus semua baris yang ada

        while (rs.next()) {
            String id = rs.getString("id");
            String nama = rs.getString("nama");
            String jenisKelamin = rs.getString("jenis_kelamin");
            String alamat = rs.getString("alamat");
            String kamera = rs.getString("kamera");
            String tambahan = rs.getString("tambahan");
            Date tglSewa = rs.getDate("tgl_sewa");
            Date tglKembali = rs.getDate("tgl_kembali");
            String pembayaran = rs.getString("pembayaran");
            int totalHari = rs.getInt("total_hari");

            // Create row object array
            Object[] row = {id, nama, jenisKelamin, alamat, kamera, tambahan, tglSewa, tglKembali, pembayaran, totalHari};

            // Add row to table model
            tableModel.addRow(row);
        }

        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btncariActionPerformed

    private void cbsdcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsdcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsdcardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnhapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapus1ActionPerformed

    private void btnhapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapus2ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalMusikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalMusikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalMusikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalMusikFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalMusikFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhapus1;
    private javax.swing.JButton btnhapus2;
    private javax.swing.JButton btntambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox cbbaterai;
    private javax.swing.JCheckBox cbsdcard;
    private javax.swing.JCheckBox cbtripod;
    private javax.swing.JComboBox<String> combobayar;
    private com.toedter.calendar.JDateChooser datekembali;
    private com.toedter.calendar.JDateChooser datesewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JList<String> listkamera;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttotalhari;
    // End of variables declaration//GEN-END:variables
    
    private ButtonGroup buttonGroupJenisKelamin;
    private void load_tabel() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Alamat");
    model.addColumn("Alat Musik");
    model.addColumn("Tambahan");
    model.addColumn("Tanggal Sewa");
    model.addColumn("Tanggal Kembali");
    model.addColumn("Pembayaran");
    model.addColumn("Total Hari");

    // Menampilkan data database ke dalam tabel
    try {
        int id = 1;
        String sql = "SELECT * FROM penyewa";
        java.sql.Connection conn = koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
        }
        
        tabel_data.setModel(model);
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }
    
}
